version: '3'
services:
  jekyll:
    image: jekyll/jekyll
    environment:
      - "JEKYLL_GITHUB_TOKEN=${JEKYLL_GITHUB_TOKEN}"
    ports:
      - "4000:4000"
    volumes:
      - ./:/srv/jekyll
      - ./vendor/bundle:/usr/local/bundle
    command:
      - jekyll
      - serve
  

